### ISSUE TITLE
Bugs with new Luas for Desmume 

### ISSUE THREAD

**Issue by nanorui86** [Real96/PokeLua#1]
I seem to have found some sort of bug when exploring the desmume Luas in Pokemon White. Shown in the snapshot, i think is a bug where Mode: Info only reads the 1st and 2nd slots on 'Party' correctly. The name of the pokemon don't match with shown on the lua. Also in the caption the save state never fades but i dont' know if this has to be with the luas. Another thing I found that coincides with what a user posted on Discord is that negative LCRNG appear in certain places.
![Error luas](https://github.com/Real96/PokeLua/assets/148982332/ec09d625-7551-48c3-b45a-8f031160879d)

**Comment by Real96** [comment]
Pls next time, when you see different bugs, open different issues.

1) Can you make a screen of the wrong info pls?

2) Save state thing is due to runasdate, so emulator problem

3) Can you tell me when does the lcrng negative number happen?

**Comment by nanorui86** [comment]
Sorry, I didn't know I had to open a new issue for each bug.

The screenshot I sent shows the capture mode info because I don't know if it has a party mode like the previous version and it shows the name of the wrong pokemon, in all modes. And also in all modes, negative LCRNGs appear as in this image.

The save state thing you where wright. 
![Error lua 2](https://github.com/Real96/PokeLua/assets/148982332/23bd0d4e-20c9-4778-9848-b2b0fdf078ae)

**Comment by Real96** [comment]
You're using the wrong mode. Capture mode is only for wilds. Pokemon info mode instead is for party/box. For this particular case, you have to use Party Stats mode. Let me know if it is correct or not

What do you do before the negative value appears?

**Comment by nanorui86** [comment]
Sorry, I already found out how to put Party/Stats mode on. But also when it shows the pokemon info, it is not correct. This screenshot is of a Pokemon I found using the RNG and with high stats and it doesn't display them correctly. I am attaching a screenshot of the Pkhex to verify it.
![Error luas 3](https://github.com/Real96/PokeLua/assets/148982332/a3711dfc-dba2-4373-9377-705e89102073)
![Error luas 2](https://github.com/Real96/PokeLua/assets/148982332/e7c3a5a5-d39b-4038-b0e6-504b1286b506)
![pkhex](https://github.com/Real96/PokeLua/assets/148982332/8326b1d7-f58d-4bac-b0c3-8e4707a69e25)

**Comment by Real96** [comment]
Can you pls try [this](https://github.com/DevonStudios/desmume/releases/tag/0.9.11) desmume build? Let me know if the error still happens

**Comment by nanorui86** [comment]
I tried that version but it crashed when I wanted to load the lua. I tried version 9.12 and I think it works fine. I'll try to try it again and confirm.

**Comment by Real96** [comment]
Thanks, let me know

**Comment by nanorui86** [comment]
Hi!, with the 9.12 Desmume version it seem working properly. All info is viewing correctly.

**Comment by Real96** [comment]
Thanks for testing!
